In [1]:
# Import libraries

import pandas as pd
import time
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
import matplotlib.pyplot as plt 
import os
import logging

In [2]:
service = Service(r'C:\Program Files (x86)\Chrome Driver\chromedriver-win64\chromedriver.exe')
driver = webdriver.Chrome(service=service)

In [3]:
# Get the page’s contents

page_url = "https://simple.m.wikipedia.org/wiki/List_of_countries"
driver.get(page_url)

In [4]:
from bs4 import BeautifulSoup
import requests

In [5]:
# Get URL

page_url =  requests.get("https://simple.m.wikipedia.org/wiki/List_of_countries")

In [6]:
# Create soup 

soup = BeautifulSoup(page_url.text, 'html.parser')

In [7]:
# Find and filter the list of countries
countries = []
for link in soup.find_all("a"):
    href = link.get("href")
    if "/wiki/" in str(href) and ":" not in str(href):
        countries.append(link.text.strip())

In [17]:
# Remove duplicates and sort the list
countries = sorted(list(set(countries)))

In [19]:
countries

['',
 'Abkhazia',
 'Adjara',
 'Afghanistan',
 'Akrotiri and Dhekelia',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Anguilla',
 'Anjouan',
 'Antarctica',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azad Kashmir',
 'Azerbaijan',
 'Azores',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bonaire',
 'Bosnia and Herzegovina',
 'Botswana',
 'Bougainville',
 'Brazil',
 'British Indian Ocean Territory',
 'British Virgin Islands',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Canary Islands',
 'Cayman Islands',
 'Central African Republic',
 'Ceuta',
 'Chad',
 'Chile',
 'China',
 'Christmas Island',
 'Cocos (Keeling) Islands',
 'Colombia',
 'Comoros',
 'Congo, Democratic Republic of the',
 'Congo, Republic of the',
 'Cook Islands',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Curaçao',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'East Timor',
 'Easter Island',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'England',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Falkland Islands',
 'Faroe Islands',
 'Fiji',
 'Finland',
 'France',
 'French Guiana',
 'French Polynesia',
 'French Southern and Antarctic Lands',
 'Gabon',
 'Gagauzia',
 'Galapagos Islands',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guernsey',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Home',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jersey',
 'Jordan',
 'Kachin State',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Korea, North',
 'Korea, South',
 'Kosovo',
 'Kurdistan',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Liberland',
 'Libya',
 'Liechtenstein',
 'List of states with limited recognition',
 'Lithuania',
 'Luxembourg',
 'Macau',
 'Madagascar',
 'Madeira',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mayotte',
 'Melilla',
 'Mexico',
 'Micronesia',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Niue',
 'Norfolk Island',
 'North Macedonia',
 'Northern Cyprus',
 'Northern Ireland',
 'Northern Mariana Islands',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Pitcairn Islands',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Romania',
 'Roraima',
 'Rotuma',
 'Russia',
 'Rwanda',
 'Réunion',
 'Saba',
 'Sahrawi Arab Democratic Republic',
 'Saint Barthelemy',
 'Saint Helena, Ascension and Tristan da Cunha',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Martin',
 'Saint Pierre and Miquelon',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Saudi Arabia',
 'Scotland',
 'Sealand',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Sint Eustatius',
 'Sint Maarten',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'Somaliland',
 'South Africa',
 'South Georgia and the South Sandwich Islands',
 'South Moluccas',
 'South Ossetia',
 'South Sudan',
 'Sovereign Military Order of Malta',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Svalbard and Jan Mayen',
 'Sweden',
 'Switzerland',
 'Syria',
 'São Tomé and Príncipe',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Tokelau',
 'Tonga',
 'Transnistria',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'United States Minor Outlying Islands',
 'United States Virgin Islands',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Vatican City',
 'Venezuela',
 'Vietnam',
 'Wa State',
 'Wales',
 'West Papua',
 'Yemen',
 'Zambia',
 'Zimbabwe',
 'sovereign states',
 'Åland']

In [27]:
# Put the countries into a dataframe

df = pd.DataFrame(countries, columns = ["Country"])
df

                   Country
0
1                 Abkhazia
2                   Adjara
3              Afghanistan
4    Akrotiri and Dhekelia
..                     ...
280                  Yemen
281                 Zambia
282               Zimbabwe
283       sovereign states
284                  Åland

[285 rows x 1 columns]

In [31]:
df = df.drop(0)
df

                   Country
1                 Abkhazia
2                   Adjara
3              Afghanistan
4    Akrotiri and Dhekelia
5                  Albania
..                     ...
280                  Yemen
281                 Zambia
282               Zimbabwe
283       sovereign states
284                  Åland

[284 rows x 1 columns]

In [33]:
file_path = 'C:/Users/nrsmi/Documents/CareerFoundry/20th_Century/countries_list.csv' 
df.to_csv(file_path, index=False)